user www-data;
worker_processes auto;
error_log /dev/stderr warn;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    server_tokens off;
    include /etc/nginx/http.d/*.conf;
    include /etc/nginx/http.extra/*.conf;
}

stream {
    include /etc/nginx/stream.d/*.conf;
}
